# config common to ZH and ZZ but specific to 2018 (nanoAOD v12 with boostedTaus private renano)
from analysis_tools import ObjectCollection, Category, Process, Dataset, Feature, Systematic
from analysis_tools.utils import DotDict


def setupBtagDeeptau(self):
#    self.btag=DotDict(tight=0.7264, medium=0.2770, loose=0.0494)
    self.deeptau=DotDict(
        vsjet=DotDict(VVVLoose=1, VVLoose=2, VLoose=3, Loose=4, Medium=5,
            Tight=6, VTight=7, VVTight=8),
        vse=DotDict(VVVLoose=1, VVLoose=2, VLoose=3, Loose=4, Medium=5,
            Tight=6, VTight=7, VVTight=8),
        vsmu=DotDict(VLoose=1, Loose=1, Medium=3, Tight=4),
    )
    # Working points for ParticleNet-MD XbbVsQCD (legacy training) from AN2021-005 (v10)
    self.particleNetMD_legacy=DotDict(high=0.9883, medium=0.9737, low=0.9088)

    self.deepboostedtau=DotDict(
        vsjet=DotDict(
            LooseWisc=0.85, # what Wisconsin is using
            VVLooseForPreprocess=-1., # the threshold to use for Preprocess (can always be tightened later)
            VLooseQCD=-1. # threshold used as lower bound for inviso QCD region 
        )
    )

def get_common_datasets_v12(self):
    """ Needs to be called with Config object as self as it needs access to self.processes """
    p = "/eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2016_HIPM_MC/"
    p_data = "/eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2016_HIPM_data/"
    hleprare = "/eos/cms/store/group/phys_higgs/HLepRare/HTT_skim_v1/Run2_2016_HIPM/"

    datasets = [
        
        ######################################## Single boson #########################################
        ###############################################################################################

        # W
        Dataset("wjets_ht1", # use WJets inclusive (wjets_MLM_aux) for normalization
            folder=p + "WJetsToLNu",
            process=self.processes.get("wjets_ht1"),
            selection="LHE_HT < 100", # warning selection is not used for PreCounter
            # We use the WJets inclusive cross-section to renormalize
            xs=self.cross_section_dict["wjets_MLM"],
            setGenWeightToOne=True,
            categorization_merging={'': 1},
            #secondary_dataset="wjets_MLM_aux", 
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("wjets_ht2",
            folder=p + "WJetsToLNu_HT-100To200",
            process=self.processes.get("wjets_ht2"),
            xs=self.cross_section_dict["wjets_ht2"],
            setGenWeightToOne=True,
            categorization_merging={'boosted_bb': 1, 'resolved_1b': 1, 'resolved_2b': 1, 'base': 5, "_sr":2},
            #secondary_dataset="wjets_ht2_aux",
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("wjets_ht3",
            folder=p + "WJetsToLNu_HT-200To400",
            process=self.processes.get("wjets_ht3"),
            xs=self.cross_section_dict["wjets_ht3"],
            setGenWeightToOne=True,
            categorization_merging={'boosted_bb': 1, 'resolved_1b': 1, 'resolved_2b': 1, 'base': 11, "_sr":3},
            #secondary_dataset="wjets_ht3_aux",
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("wjets_ht4",
            folder=p + "WJetsToLNu_HT-400To600",
            process=self.processes.get("wjets_ht4"),
            xs=self.cross_section_dict["wjets_ht4"],
            setGenWeightToOne=True,
            categorization_merging={'boosted_bb': 1, 'resolved_1b': 1, 'resolved_2b': 1, 'base': 10, "_sr":3},
            #secondary_dataset="wjets_ht4_aux",
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("wjets_ht5",
            folder=p + "WJetsToLNu_HT-600To800",
            process=self.processes.get("wjets_ht5"),
            xs=self.cross_section_dict["wjets_ht5"],
            setGenWeightToOne=True,
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 5, "_sr":2},
            #secondary_dataset="wjets_ht5_aux",
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("wjets_ht6",
            folder=p + "WJetsToLNu_HT-800To1200",
            process=self.processes.get("wjets_ht6"),
            xs=self.cross_section_dict["wjets_ht6"],
            setGenWeightToOne=True,
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 5, "_sr":2},
            #secondary_dataset="wjets_ht6_aux",
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("wjets_ht7",
            folder=p + "WJetsToLNu_HT-1200To2500",
            process=self.processes.get("wjets_ht7"),
            xs=self.cross_section_dict["wjets_ht7"],
            setGenWeightToOne=True,
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 5, "_sr":2},
            #secondary_dataset="wjets_ht7_aux",
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("wjets_ht8",
            folder=p + "WJetsToLNu_HT-2500ToInf",
            process=self.processes.get("wjets_ht8"),
            xs=self.cross_section_dict["wjets_ht8"],
            setGenWeightToOne=True,
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3, "_sr":1},
            #secondary_dataset="wjets_ht8_aux",
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),

        # DY
        Dataset("dy",
            folder=p + "DYJetsToLL_M-50-amcatnloFXFX",
            process=self.processes.get("dy_incl"),
            xs=self.cross_section_dict["dy"],
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 2, 'resolved_2b_HPSTau': 2, 'base': 10, "_sr":5},
            merging={
                "tautau": 10,
                "etau": 10,
                "mutau": 10,
                "resolved_1b_HPSTau": 2,
                "resolved_2b_HPSTau": 2,
                "boosted" : 1,
                "elliptical_cut": 5
            },
            #secondary_dataset="dy_aux",
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul", "limited", "limitedBoostedTau"]),

        Dataset("dy_ptz1",
            folder=p + "DYJetsToLL_LHEFilterPtZ-0To50-amcatnloFXFX",
            process=self.processes.get("dy_ptz1"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_ptz1"],
            #secondary_dataset="dy_ptz1_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 2, 'resolved_2b_HPSTau': 1, 'base': 10, "_sr":5},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("dy_ptz2",
            folder=p + "DYJetsToLL_LHEFilterPtZ-50To100-amcatnloFXFX",
            process=self.processes.get("dy_ptz2"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_ptz2"],
            #secondary_dataset="dy_ptz2_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 2, 'resolved_2b_HPSTau': 1, 'base': 12, "_sr":5},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("dy_ptz3",
            folder=p + "DYJetsToLL_LHEFilterPtZ-100To250-amcatnloFXFX",
            process=self.processes.get("dy_ptz3"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_ptz3"],
            #secondary_dataset="dy_ptz3_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 2, 'resolved_2b_HPSTau': 1, 'base': 15, "_sr":5},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("dy_ptz4",
            folder=p + "DYJetsToLL_LHEFilterPtZ-250To400-amcatnloFXFX",
            process=self.processes.get("dy_ptz4"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_ptz4"],
            #secondary_dataset="dy_ptz4_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 2, 'resolved_2b_HPSTau': 1, 'base': 15, "_sr":5},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("dy_ptz5",
            folder=p + "DYJetsToLL_LHEFilterPtZ-400To650-amcatnloFXFX",
            process=self.processes.get("dy_ptz5"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_ptz5"],
            #secondary_dataset="dy_ptz5_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3, "_sr":1},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("dy_ptz6",
            folder=p + "DYJetsToLL_LHEFilterPtZ-650ToInf-amcatnloFXFX",
            process=self.processes.get("dy_ptz6"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_ptz6"],
            #secondary_dataset="dy_ptz6_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3, "_sr":1},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),

        Dataset("dy_0j",
            folder=p + "DYJetsToLL_0J-amcatnloFXFX",
            process=self.processes.get("dy_0j"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_0j"],
            #secondary_dataset="dy_0j_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul"]),
        Dataset("dy_1j",
            folder=p + "DYJetsToLL_1J-amcatnloFXFX",
            process=self.processes.get("dy_1j"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_1j"],
            #secondary_dataset="dy_1j_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 4, "_sr":1},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul"]),
        Dataset("dy_2j",
            folder=p + "DYJetsToLL_2J-amcatnloFXFX",
            process=self.processes.get("dy_2j"),
            xs=self.cross_section_dict["dy"],
            #xs=self.cross_section_dict["dy_2j"],
            #secondary_dataset="dy_2j_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 2, 'resolved_2b_HPSTau': 1, 'base': 10, "_sr":4},
            prefix="eos.grif.fr//",
            stitchingNormalization=True,
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),

        # EWK
        Dataset("ewk_z",
            folder=p + "EWK_ZTo2L",
            process=self.processes.get("ewk_z"),
            xs=self.cross_section_dict["ewk_z"],
            splitting=200000,
            #secondary_dataset="ewk_z_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ewk_wplus",
            folder=p + "EWK_WplusToLNu",
            process=self.processes.get("ewk_wplus"),
            xs=self.cross_section_dict["ewk_wplus"],
            #secondary_dataset="ewk_wplus_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ewk_wminus",
            folder=p + "EWK_WminusToLNu",
            process=self.processes.get("ewk_wminus"),
            xs=self.cross_section_dict["ewk_wminus"],
            #secondary_dataset="ewk_wminus_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),

        ######################################## Top ##################################################
        ###############################################################################################

        # TT
        Dataset("tt_dl",
            folder=p + "TTTo2L2Nu",
            process=self.processes.get("tt_dl"),
            xs=self.cross_section_dict["tt_dl"],
            merging={
                "tautau": 20,
                "mutau": 20,
                "etau": 40,
                "resolved_1b": 30,
                "resolved_2b": 20,
                "boosted" : 1,
                "elliptical_cut": 20,
            },
            # scaling=(0.96639, 0.00863), # temporaily disabled until we compute our ou SF
            #secondary_dataset="tt_dl_aux",
            categorization_merging={'boosted_bb_boostedTau': 5, 'boosted_bb_HPSTau': 6, 'resolved_1b_HPSTau': 16, 'resolved_2b_HPSTau': 13, 'base': 47, "_sr":40},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limited", "limitedBoostedTau"]),
        Dataset("tt_sl",
            folder=p + "TTToSemiLeptonic",
            process=self.processes.get("tt_sl"),
            xs=self.cross_section_dict["tt_sl"],
            merging={
                "tautau": 20,
                "mutau": 60,
                "etau": 40,
                "resolved_1b_HPSTau": 30,
                "resolved_2b_HPSTau": 20,
                "boosted_bb_boostedTau": 4,
                "boosted" : 1,
                "elliptical_cut": 40
            },
            # scaling=(0.96639, 0.00863), # temporaily disabled until we compute our ou SF
            #secondary_dataset="tt_sl_aux",
            categorization_merging={'boosted_bb_boostedTau': 10, 'boosted_bb_HPSTau': 15, 'resolved_1b_HPSTau': 62, 'resolved_2b_HPSTau': 36, 'base': 155, "_sr":100},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limited", "limitedBoostedTau"]),
        Dataset("tt_fh",
            folder=p + "TTToHadronic",
            process=self.processes.get("tt_fh"),
            xs=self.cross_section_dict["tt_fh"],
            # scaling=(0.96639, 0.00863), # temporaily disabled until we compute our ou SF
            #secondary_dataset="tt_fh_aux",
            categorization_merging={'boosted_bb_boostedTau': 5, 'boosted_bb_HPSTau': 5, 'resolved_1b_HPSTau': 23, 'resolved_2b_HPSTau': 13, 'base': 48, "_sr":40},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),

        # TW
        Dataset("st_tw_antitop",
            folder=p + "ST_tW_antitop_5f_InclusiveDecays",
            process=self.processes.get("tw"),
            xs=self.cross_section_dict["st_tw_antitop"],
            #secondary_dataset="st_tw_antitop_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3, "_sr":2},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("st_tw_top",
            folder=p + "ST_tW_top_5f_InclusiveDecays",
            process=self.processes.get("tw"),
            xs=self.cross_section_dict["st_tw_top"],
            #secondary_dataset="st_tw_top_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3, "_sr":2},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),

        # singleT
        Dataset("st_antitop",
            folder=p + "ST_t-channel_antitop_4f_InclusiveDecays",
            process=self.processes.get("singlet"),
            xs=self.cross_section_dict["st_antitop"],
            #secondary_dataset="st_antitop_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 3, 'resolved_2b_HPSTau': 1, 'base': 6, "_sr":5},
            merging={ 
                "resolved_2b_HPSTau": 2,
                "resolved_1b_HPSTau": 5,
            },
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("st_top",
            folder=p + "ST_t-channel_top_4f_InclusiveDecays",
            process=self.processes.get("singlet"),
            xs=self.cross_section_dict["st_top"],
            #secondary_dataset="st_top_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 5, "_sr":3},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),

        ######################################## Di- and Tri-boson ####################################
        ###############################################################################################

        # VV
        Dataset("zz_dl",
            folder=p + "ZZTo4L",
            process=self.processes.get("zz"),
            xs=self.cross_section_dict["zz_dl"],
            #secondary_dataset="zz_dl_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 4, "_sr":2},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "limitedBoostedTau"]),
        Dataset("zz_fh",
            folder=p + "ZZTo4Q",
            process=self.processes.get("zz"),
            xs=self.cross_section_dict["zz_fh"],
            #secondary_dataset="zz_fh_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("zz_lnu",
            folder=p + "ZZTo2L2Nu",
            process=self.processes.get("zz"),
            xs=self.cross_section_dict["zz_lnu"],
            #secondary_dataset="zz_lnu_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3, "_sr":2},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("zz_qnu",
            folder=p + "ZZTo2Q2Nu",
            process=self.processes.get("zz"),
            xs=self.cross_section_dict["zz_qnu"],
            #secondary_dataset="zz_qnu_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("wz_lllnu",
            folder=p + "WZTo3LNu",
            process=self.processes.get("wz"),
            xs=self.cross_section_dict["wz_lllnu"],
            #secondary_dataset="wz_lllnu_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("wz_lnuqq",
            folder=p + "WZTo1L1Nu2Q",
            process=self.processes.get("wz"),
            xs=self.cross_section_dict["wz_lnuqq"],
            #secondary_dataset="wz_lnuqq_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("wz_lnununu",
            folder=p + "WZTo1L3Nu",
            process=self.processes.get("wz"),
            xs=self.cross_section_dict["wz_lnununu"],
            #secondary_dataset="wz_lnununu_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("wz_llqq",
            folder=p + "WZTo2Q2L",
            process=self.processes.get("wz"),
            xs=self.cross_section_dict["wz_llqq"],
            #secondary_dataset="wz_llqq_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 8, "_sr":4},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ww_llnunu",
            folder=p + "WWTo2L2Nu",
            process=self.processes.get("ww"),
            xs=self.cross_section_dict["ww_llnunu"],
            #secondary_dataset="ww_llnunu_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ww_lnuqq",
            folder=p + "WWTo1L1Nu2Q",
            process=self.processes.get("ww"),
            xs=self.cross_section_dict["ww_lnuqq"],
            #secondary_dataset="ww_lnuqq_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 8, "_sr":4},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ww_qqqq",
            folder=p + "WWTo4Q",
            process=self.processes.get("ww"),
            xs=self.cross_section_dict["ww_qqqq"],
            #secondary_dataset="ww_qqqq_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 4, "_sr":1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),

        # VVV
        Dataset("zzz",
            folder=p + "ZZZ",
            process=self.processes.get("zzz"),
            xs=self.cross_section_dict["zzz"],
            #secondary_dataset="zzz_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("wzz",
            folder=p + "WZZ",
            process=self.processes.get("wzz"),
            xs=self.cross_section_dict["wzz"],
            #secondary_dataset="wzz_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("www",
            folder=p + "WWW_4F",
            process=self.processes.get("www"),
            xs=self.cross_section_dict["www"],
            #secondary_dataset="www_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("wwz",
            folder=p + "WWZ_4F",
            process=self.processes.get("wwz"),
            xs=self.cross_section_dict["wwz"],
            #secondary_dataset="wwz_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),

        ######################################## Others ###############################################
        ###############################################################################################

        # TTX
        Dataset("ttw_lnu",
            folder=p + "TTWJetsToLNu",
            process=self.processes.get("ttw"),
            xs=self.cross_section_dict["ttw_lnu"],
            #secondary_dataset="ttw_lnu_aux",
            categorization_merging={'boosted_bb_boostedTau': 2, 'boosted_bb_HPSTau': 2, 'resolved_1b_HPSTau': 4, 'resolved_2b_HPSTau': 7, 'base': 10, "_sr":10},
            merging={ 
                "resolved_2b_HPSTau": 4,
                "resolved_1b_HPSTau": 7,
            },
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ttw_qq",
            folder=p + "TTWJetsToQQ",
            process=self.processes.get("ttw"),
            xs=self.cross_section_dict["ttw_qq"],
            #secondary_dataset="ttw_qq_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ttww",
            folder=p + "TTWW",
            process=self.processes.get("ttww"),
            xs=self.cross_section_dict["ttww"],
            #secondary_dataset="ttww_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ttwz",
            folder=p + "TTWZ",
            process=self.processes.get("ttwz"),
            xs=self.cross_section_dict["ttwz"],
            #secondary_dataset="ttwz_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ttwh",
            folder=p + "TTWH",
            process=self.processes.get("ttwh"),
            xs=self.cross_section_dict["ttwh"],
            #secondary_dataset="ttwh_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ttzh",
            folder=p + "TTZH",
            process=self.processes.get("ttzh"),
            xs=self.cross_section_dict["ttzh"],
            #secondary_dataset="ttzh_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ttz_llnunu",
            folder=p + "TTZToLLNuNu_M-10",
            process=self.processes.get("ttz"),
            xs=self.cross_section_dict["ttz_llnunu"],
            #secondary_dataset="ttz_llnunu_aux",
            categorization_merging={'boosted_bb_boostedTau': 4, 'boosted_bb_HPSTau': 5, 'resolved_1b_HPSTau': 7, 'resolved_2b_HPSTau': 4, 'base': 10, "_sr":15},
            merging={ 
                "resolved_2b_HPSTau": 4,
                "resolved_1b_HPSTau": 7,
            },
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ttz_qq",
            folder=p + "TTZToQQ",
            process=self.processes.get("ttz"),
            xs=self.cross_section_dict["ttz_qq"],
            #secondary_dataset="ttz_qq_aux",
            categorization_merging={'boosted_bb_boostedTau': 2, 'boosted_bb_HPSTau': 2, 'resolved_1b_HPSTau': 10, 'resolved_2b_HPSTau': 7, 'base': 14, "_sr":14},
            merging={ 
                "resolved_2b_HPSTau": 7,
                "resolved_1b_HPSTau": 10,
            },
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("ttzz",
            folder=p + "TTZZ",
            process=self.processes.get("ttzz"),
            xs=self.cross_section_dict["ttzz"],
            #secondary_dataset="ttzz_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),

        ######################################## Higgs ###############################################
        ###############################################################################################

        ## ZH_HToBB_ZToLL and ZHToTauTau are in ZZ and ZH specific configurations 
        
        # ZH_hbb       # removed since the dataset is not available TODO FIXME
        # Dataset("zh_hbb_zqq",
        #     folder=p + "ZH_Hbb_Zqq",
        #     process=self.processes.get("zh_hbb"),# the associated process is defined separately in ZZ and ZH configs since the parent process is different in each case
        #     xs=self.cross_section_dict["zh_hbb_zqq"],
        #     #secondary_dataset="zh_hbb_zqq_aux",
        #     # categorization_max_events=10000,
        #     prefix="eos.grif.fr//",
        #     tags=["ul", "nanoV10", "bul"]),
            
        # WH_htt
        Dataset("wminush_htt",
            folder=p + "WminusHToTauTau_M125",
            process=self.processes.get("wh_htt"),
            # prefix="xrootd-cms.infn.it//",
            xs=self.cross_section_dict["wminush_htt"],
            #secondary_dataset="wminush_htt_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3, "_sr":2},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        Dataset("wplush_htt",
            folder=p + "WplusHToTauTau_M125",
            process=self.processes.get("wh_htt"),
            # prefix="xrootd-cms.infn.it//",
            xs=self.cross_section_dict["wplush_htt"],
            #secondary_dataset="wminush_htt_aux",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3, "_sr":2},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),    

        # vbf_htt (removed cause it takes very long and it's not in the datacard for HHbbtt) 
        # Dataset("vbf_htt",
        #     folder=p + "VBFHToTauTau_M125",
        #     process=self.processes.get("vbf_htt"),
        #     # prefix="xrootd-cms.infn.it//",
        #     xs=self.cross_section_dict["vbf_htt"],
        #     #secondary_dataset="vbf_htt_aux",
        #     # categorization_max_events=10000,
        #     prefix="eos.grif.fr//",
        #     tags=["ul", "nanoV10", "bul"]),

        # ttH_hbb 
        Dataset("tth_bb",
            folder=p + "ttHTobb_M125",
            process=self.processes.get("tth_bb"),
            xs=self.cross_section_dict["tth_bb"],
            #secondary_dataset="tth_bb_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        # ttH_htt (not in the datacard)
        Dataset("tth_tautau",
            folder=p + "ttHToTauTau_M125",
            process=self.processes.get("tth_tautau"),
            # prefix="xrootd-cms.infn.it//",
            xs=self.cross_section_dict["tth_tautau"],
            #secondary_dataset="tth_tautau_aux",
            categorization_merging={'boosted_bb_boostedTau': 8, 'boosted_bb_HPSTau': 10, 'resolved_1b_HPSTau': 30, 'resolved_2b_HPSTau': 30, 'base': 40, "_sr":30},
            merging={
                "resolved_1b_HPSTau" : 30,
                "resolved_2b_HPSTau" : 30,
                "boosted_bb_HPSTau" : 5,
                "boosted_bb_boostedTau" : 2,
            },
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        # ttH_hnonbb (removed cause it takes very long and it's not in the datacard for HHbbtt) 
        # Dataset("tth_nonbb",
        #     folder=p + "ttHToNonbb_M125",
        #     process=self.processes.get("tth_nonbb"),
        #     # prefix="xrootd-cms.infn.it//",
        #     xs=self.cross_section_dict["tth_nonbb"],
        #     #secondary_dataset="tth_nonbb_aux",
        #     # categorization_max_events=10000,
        #     prefix="eos.grif.fr//",
        #     tags=["ul", "nanoV10", "bul"]),

        # ggH_ZZ
        Dataset("ggH_ZZ",
            folder=p + "ggHToZZTo2L2Q",
            process=self.processes.get("ggH_ZZ"),
            # prefix="xrootd-cms.infn.it//",
            xs=self.cross_section_dict["ggH_ZZ"],
            #secondary_dataset="ggH_ZZ_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),

        ######################################## HH bbtautau ##########################################
        ###############################################################################################

        # ggf
        Dataset("ggf_sm",
            folder=p + "GluGluToHHTo2B2Tau_node_SM",
            process=self.processes.get("ggf_sm"),
            xs=self.cross_section_dict["ggf_sm"],
            #secondary_dataset="ggf_sm_aux",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul"]),
        # # vbf 
        # Dataset("vbf_sm",
        #     dataset="",
        #     process=self.processes.get("vbf_sm"),
        #     # prefix="xrootd-cms.infn.it//",
        #     xs=self.cross_section_dict["vbf_sm"],
        #     #secondary_dataset="vbf_sm_aux",
        #     # categorization_max_events=10000,
        #     prefix="eos.grif.fr//",
        #     tags=["ul", "nanoV10", "bul"]),

        ######################################## Data #################################################
        ###############################################################################################

        # Tau 2016 HIPM
        Dataset("data_tau_a",
            folder=hleprare + "Tau_Run2016B",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="B",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_tau_b",
            folder=hleprare + "Tau_Run2016C",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="C",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_tau_c",
            folder=hleprare + "Tau_Run2016D",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="D",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_tau_d",
            folder=hleprare + "Tau_Run2016E",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="E",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_tau_e",
            folder=hleprare + "Tau_Run2016F",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="F",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),

        # SingleElectron 2016 HIPM
        Dataset("data_etau_a",
            folder=hleprare + "SingleElectron_Run2016B",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="B",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 2, 'resolved_2b_HPSTau': 1, 'base': 3},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_etau_b",
            folder=hleprare + "SingleElectron_Run2016C",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="C",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_etau_c",
            folder=hleprare + "SingleElectron_Run2016D",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="D",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 2},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_etau_d",
            folder=hleprare + "SingleElectron_Run2016E",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="E",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 2},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_etau_e",
            folder=hleprare + "SingleElectron_Run2016F",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="F",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),

        # SingleMuon 2016 HIPM
        Dataset("data_mutau_a",
            folder=hleprare + "SingleMuon_Run2016B",
            selection="pairType == 0",
            process=self.processes.get("data_mutau"),
            runEra="B",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 2},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_mutau_b",
            folder=hleprare + "SingleMuon_Run2016C",
            process=self.processes.get("data_mutau"),
            selection="pairType == 0",
            runEra="C",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_mutau_c",
            folder=hleprare + "SingleMuon_Run2016D",
            process=self.processes.get("data_mutau"),
            selection="pairType == 0",
            runEra="D",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_mutau_d",
            folder=hleprare + "SingleMuon_Run2016E",
            process=self.processes.get("data_mutau"),
            selection="pairType == 0",
            runEra="E",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        Dataset("data_mutau_e",
            folder=hleprare + "SingleMuon_Run2016F",
            process=self.processes.get("data_mutau"),
            selection="pairType == 0",
            runEra="F",
            categorization_merging={'': 1},
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10", "bul", "data", "hpsData"]),
        
        # MET 
        Dataset("data_met_a1",
            folder=p_data + "MET_Run2016B1",
            process=self.processes.get("data_met"),
            selection="isBoostedTau",
            runEra="B1",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "data", "met"]),
        Dataset("data_met_a",
            folder=p_data + "MET_Run2016B2",
            process=self.processes.get("data_met"),
            selection="isBoostedTau",
            runEra="B",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "data", "met"]),
        Dataset("data_met_b",
            folder=p_data + "MET_Run2016C",
            process=self.processes.get("data_met"),
            selection="isBoostedTau",
            runEra="C",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "data", "met"]),
        Dataset("data_met_c",
            folder=p_data + "MET_Run2016D",
            process=self.processes.get("data_met"),
            selection="isBoostedTau",
            runEra="D",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 2},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "data", "met"]),
        Dataset("data_met_d",
            folder=p_data + "MET_Run2016E",
            process=self.processes.get("data_met"),
            selection="isBoostedTau",
            runEra="E",
            categorization_merging={'boosted_bb_boostedTau': 1, 'boosted_bb_HPSTau': 1, 'resolved_1b_HPSTau': 1, 'resolved_2b_HPSTau': 1, 'base': 3},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "data", "met"]),
        Dataset("data_met_e",
            folder=p_data + "MET_Run2016F",
            process=self.processes.get("data_met"),
            selection="isBoostedTau",
            runEra="F",
            categorization_merging={'': 1},
            prefix="eos.grif.fr//",
            tags=["ul", "nanoV10", "bul", "data", "met"]),

    ]
    datasets = ObjectCollection(datasets)

    return datasets