puweight:
    name: puWeightRDF
    path: Corrections.LUM.puWeight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')

# UL only
# puweightCor:
    # name: puWeightRDF
    # path: Corrections.LUM.puWeightCor
    # parameters:
        # isMC: self.dataset.process.isMC
        # year: self.config.year
        # isUL: self.dataset.has_tag('ul')

2:
    name: MetFilterRDF
    path: Base.Modules.METfilters
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

tauSF:
    name: tauSFRDF
    path: Corrections.TAU.tauCorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')

hhlepton:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runPeriod: self.dataset.runPeriod
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        filter: True

hhleptonVar:
    name: HHLeptonVarRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC


jet_smearing:
    name: jetSmearerRDF
    path: Corrections.JME.smearing
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        jerTag: self.config.year
        isUL: self.dataset.has_tag('ul')


jet_smear_val:
    name: jetVarRDF
    path: Corrections.JME.smearing
    parameters:
        isMC: self.dataset.process.isMC


met_smearing:
    name: metSmearerRDF
    path: Corrections.JME.smearing
    parameters:
        isMC: self.dataset.process.isMC


hhjets:
    name: HHJetsRDF
    path: Tools.Tools.HHJets
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        isUL: self.dataset.has_tag('ul')
        met_smear_tag: smeared
        filter: True


# dyscaling:
    # name: DYscalingRDF
    # path: Tools.Tools.dyreweighting
    # parameters:
        # year: self.config.year
        # isDY: self.dataset.process.get_aux('isDY', False)


# svfit:
    # name: SVFitRDF
    # path: Tools.Tools.svfit
    # parameters:
        # isMC: self.dataset.process.isMC
        # met_smear_tag: smeared


# hh:
    # name: HHKinFitRDF
    # path: Tools.Tools.hh
    # parameters:
        # isMC: self.dataset.process.isMC
        # met_smear_tag: smeared


# hhvar:
    # name: HHVarRDF
    # path: Tools.Tools.hh
    # parameters:
        # isMC: self.dataset.process.isMC
        # met_smear_tag: smeared


# trigSF:
    # name: Htt_trigSFRDF
    # path: Tools.Tools.Htt_trigSF
    # parameters:
        # year: self.config.year
        # isMC: self.dataset.process.isMC
        # isUL: self.dataset.has_tag('ul')


# PUjetID_SF:
    # name: PUjetID_SFRDF
    # path: Corrections.JME.PUjetID_SF
    # parameters:
        # year: self.config.year
        # isMC: self.dataset.process.isMC
        # isUL: self.dataset.has_tag('ul')

# 3_w2:
    # name: prescaleWeightRDF
    # path: Tools.Tools.weight
    # parameters:
        # isMC: self.dataset.process.isMC
        # year: self.config.year


# 4_w2:
    # name: prefiringWeightRDF
    # path: Base.Modules.prefiringWeight
    # parameters:
        # isMC: self.dataset.process.isMC
        # isUL: self.dataset.has_tag('ul')


# # tauSF:
    # # name: tauSFRDF
    # # path: Corrections.TAU.tauCorrections
    # # parameters:
        # # isMC: self.dataset.process.isMC
        # # year: self.config.year
        # # isUL: self.dataset.has_tag('ul')

# # muSF:
    # # name: muSFRDF
    # # path: Corrections.MUO.muCorrections
    # # parameters:
        # # isMC: self.dataset.process.isMC
        # # year: self.config.year
        # # isUL: self.dataset.has_tag('ul')

# # eleSD:
    # # name: eleSFRDF
    # # path: Corrections.EGM.eleCorrections
    # # parameters:
        # # isMC: self.dataset.process.isMC
        # # year: self.config.year
        # # isUL: self.dataset.has_tag('ul')


# # idAndIsoSF:
    # # name: dauIdIsoSFRDF
    # # path: Tools.Tools.dauIdIso
    # # parameters:
        # # isMC: self.dataset.process.isMC


# btag:
    # name: btag_SFRDF
    # path: Corrections.BTV.btag_SF
    # parameters:
        # isMC: self.dataset.process.isMC
        # year: self.config.year
        # isUL: self.dataset.has_tag('ul')
