# This configuration is used for Categorization step
# It is not analysis related (managed by AnalysisType) 
# It computes the variables needed for the DNN training

hhjetsCategory:
    name: JetCategoryRDF
    path: Tools.Tools.HHJets
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        btag_wp: self.config.btag_algo_wps.medium
        fatjet_bbtag_wp: self.config.boosted_bb_tagging_wp

jetCategoryCheck:
    name: JetCategoryCheckRDF
    path: Tools.Tools.HHJets
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        jet_category: self.category.get_aux("jet_category", None)

jetCategoryFilter: # filter to keep only categories for DNN input computation. Not strictly necessary, but faster and avoids tons of printouts (esp. for signal which is run without hhjets filter)
    name: JetCategoryFilterRDF
    path: Tools.Tools.HHJets
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC


zz:
    name: HHKinFitRDF
    path: Tools.Tools.hh
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        met_smear_tag: tes_electron_xycorr
        AnalysisType: self.config.get_aux('AnalysisType', False)

zzvar:
    name: HHVarRDF
    path: Tools.Tools.hh
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        met_smear_tag: tes_electron_xycorr
        AnalysisType: self.config.get_aux('AnalysisType', False)

zzdnninputs:
    name: HHDNNInputRDF
    path: Tools.Tools.HHDNN
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        AnalysisType: self.config.get_aux('AnalysisType', False)
        btag_wps: self.config.btag_algo_wps
        cvl_wps: self.config.ctag_algo_wps.CvL
        cvb_wps: self.config.ctag_algo_wps.CvB
        met_smear_tag: tes_electron_xycorr
        feature_file: src/cms_runII_dnn_models/models/arc_checks/zz_bbtt/2024-11-16/all_features.txt


dystitching:
    name: DYstitchingRDF
    path: Tools.Tools.dyreweighting
    parameters:
        isDY: self.dataset.process.get_aux('isDY', False)
        year: self.config.year
        runPeriod: self.config.runPeriod
