# preplot modules
dystitching:
    name: DYstitchingRDF
    path: Tools.Tools.dyreweighting
    parameters:
        isDY: self.dataset.process.get_aux('isDY', False)
        year: self.config.year
        runPeriod: self.config.runPeriod
