# config common to ZH and ZZ but specific to 2016 HIPM (nanoAOD v10)
from analysis_tools import ObjectCollection, Category, Process, Dataset, Feature, Systematic
from analysis_tools.utils import DotDict

def get_2016_HIPM_v12_weights():
    weights = DotDict()
    weights.default = "1"
    # weights.total_events_weights = ["genWeight", "puWeight", "DYstitchWeight"]
    weights.total_events_weights = ["genWeight", "puWeight"]

    weights.mutau = ["genWeight", "puWeight", "DYstitchEasyWeight", "prescaleWeight", 
        "trigSF", "idAndIsoAndFakeSF", "PUjetID_SF",
        "bTagweightReshape"] # removed L1PreFiringWeight for UL
    weights.etau = weights.mutau
    weights.tautau = weights.mutau
    weights.base_selection = weights.mutau
    weights.base = weights.mutau

    # weights.channels_mult = {channel: jrs(weights.channels[channel], op="*")
        # for channel in weights.channels}
    return weights

def setupBtagDeeptau(self):
    self.btag=DotDict(tight=0.7264, medium=0.2770, loose=0.0494)
    self.deeptau=DotDict(
        vsjet=DotDict(VVVLoose=1, VVLoose=2, VLoose=3, Loose=4, Medium=5,
            Tight=6, VTight=7, VVTight=8),
        vse=DotDict(VVVLoose=1, VVLoose=2, VLoose=3, Loose=4, Medium=5,
            Tight=6, VTight=7, VVTight=8),
        vsmu=DotDict(VLoose=1, Loose=1, Medium=3, Tight=4),
    )

def get_common_datasets_v12(self):
    """ Needs to be called with Config object as self as it needs access to self.processes """
    p = "/eos/cms/store/group/phys_higgs/HLepRare/HTT_skim_v1/Run2_2016_HIPM/"

    datasets = [
        
        ######################################## Single boson #########################################
        ###############################################################################################

        # W
        # Dataset("wjets_FXFX",
        #     folder=p + "WJetsToLNu-amcatnloFXFX",
        #     process=self.processes.get("wjets_fxfx"),
        #     xs=61526.7,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_FXFX_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),

        # Dataset("wjets_FXFX_0j",
        #     folder=p + "W0JetsToLNu-amcatnloFXFX",
        #     process=self.processes.get("wjets_fxfx_0j"),
        #     xs=52780.0/64888.0*61526.7,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_FXFX_0j_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),
        # Dataset("wjets_FXFX_1j",
        #     folder=p + "W1JetsToLNu-amcatnloFXFX",
        #     process=self.processes.get("wjets_fxfx_1j"),
        #     xs=8832.0/64888.0*61526.7,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_FXFX_1j_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),
        # Dataset("wjets_FXFX_2j",
        #     folder=p + "W2JetsToLNu-amcatnloFXFX",
        #     process=self.processes.get("wjets_fxfx_2j"),
        #     xs=3276.0/64888.0*61526.7,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_FXFX_2j_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),

        # not used in the current wjets stitching method
        # Dataset("wjets_MLM",
        #     folder=p + "WJetsToLNu",
        #     process=self.processes.get("wjets_mlm"),
        #     xs=61526.7,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_MLM_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),
        
        # Dataset("wjets_MLM_1j",
        #     folder=p + "W1JetsToLNu",
        #     process=self.processes.get("wjets_mlm_1j"),
        #     xs=9024.0,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_MLM_1j_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),
        # Dataset("wjets_MLM_2j",
        #     folder=p + "W2JetsToLNu",
        #     process=self.processes.get("wjets_mlm_2j"),
        #     xs=2832.0,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_MLM_2j_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),
        # Dataset("wjets_MLM_3j",
        #     folder=p + "W3JetsToLNu",
        #     process=self.processes.get("wjets_mlm_3j"),
        #     xs=820.7,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_MLM_3j_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),
        # Dataset("wjets_MLM_4j",
        #     folder=p + "W4JetsToLNu",
        #     process=self.processes.get("wjets_mlm_4j"),
        #     xs=385.5,
        #     # categorization_max_events=10000,
        #     secondary_dataset="wjets_MLM_4j_aux",
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),

        Dataset("wjets_ht1",
            folder=p + "WJetsToLNu",
            process=self.processes.get("wjets_ht1"),
            selection="(LHE_HT < 100)",
            xs=61526.7, # NNLO inclusive
            # categorization_max_events=10000,
            secondary_dataset="wjets_MLM_aux",
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wjets_ht2",
            folder=p + "WJetsToLNu_HT-100To200",
            process=self.processes.get("wjets_ht2"),
            xs=1244.0 * 61526.7 / 53870, # LO * NNLO(incl)/LO(incl)
            setGenWeightToOne=True,
            # categorization_max_events=10000,
            secondary_dataset="wjets_ht2_aux",
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wjets_ht3",
            folder=p + "WJetsToLNu_HT-200To400",
            process=self.processes.get("wjets_ht3"),
            xs=337.8 * 61526.7 / 53870, # LO * NNLO(incl)/LO(incl)
            setGenWeightToOne=True,
            # categorization_max_events=10000,
            secondary_dataset="wjets_ht3_aux",
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wjets_ht4",
            folder=p + "WJetsToLNu_HT-400To600",
            process=self.processes.get("wjets_ht4"),
            xs=44.93 * 61526.7 / 53870, # LO * NNLO(incl)/LO(incl)
            setGenWeightToOne=True,
            # categorization_max_events=10000,
            secondary_dataset="wjets_ht4_aux",
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wjets_ht5",
            folder=p + "WJetsToLNu_HT-600To800",
            process=self.processes.get("wjets_ht5"),
            xs=11.19 * 61526.7 / 53870, # LO * NNLO(incl)/LO(incl)
            setGenWeightToOne=True,
            # categorization_max_events=10000,
            secondary_dataset="wjets_ht5_aux",
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wjets_ht6",
            folder=p + "WJetsToLNu_HT-800To1200",
            process=self.processes.get("wjets_ht6"),
            xs=4.926 * 61526.7 / 53870, # LO * NNLO(incl)/LO(incl)
            setGenWeightToOne=True,
            # categorization_max_events=10000,
            secondary_dataset="wjets_ht6_aux",
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wjets_ht7",
            folder=p + "WJetsToLNu_HT-1200To2500",
            process=self.processes.get("wjets_ht7"),
            xs=1.152 * 61526.7 / 53870, # LO * NNLO(incl)/LO(incl)
            setGenWeightToOne=True,
            # categorization_max_events=10000,
            secondary_dataset="wjets_ht7_aux",
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wjets_ht8",
            folder=p + "WJetsToLNu_HT-2500ToInf",
            process=self.processes.get("wjets_ht8"),
            xs=0.02646 * 61526.7 / 53870, # LO * NNLO(incl)/LO(incl)
            setGenWeightToOne=True,
            # categorization_max_events=10000,
            secondary_dataset="wjets_ht8_aux",
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        # DY
        Dataset("dy",
            folder=p + "DYJetsToLL_M-50-amcatnloFXFX",
            process=self.processes.get("dy_incl"),
            xs=6424.0,
            merging={
                "tautau": 10,
                "etau": 10,
                "mutau": 10,
            },
            secondary_dataset="dy_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        Dataset("dy_ptz1",
            folder=p + "DYJetsToLL_LHEFilterPtZ-0To50-amcatnloFXFX",
            process=self.processes.get("dy_ptz1"),
            xs=1485.0,
            secondary_dataset="dy_ptz1_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("dy_ptz2",
            folder=p + "DYJetsToLL_LHEFilterPtZ-50To100-amcatnloFXFX",
            process=self.processes.get("dy_ptz2"),
            xs=397.4,
            secondary_dataset="dy_ptz2_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("dy_ptz3",
            folder=p + "DYJetsToLL_LHEFilterPtZ-100To250-amcatnloFXFX",
            process=self.processes.get("dy_ptz3"),
            xs=97.2,
            secondary_dataset="dy_ptz3_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("dy_ptz4",
            folder=p + "DYJetsToLL_LHEFilterPtZ-250To400-amcatnloFXFX",
            process=self.processes.get("dy_ptz4"),
            xs=3.701,
            secondary_dataset="dy_ptz4_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("dy_ptz5",
            folder=p + "DYJetsToLL_LHEFilterPtZ-400To650-amcatnloFXFX",
            process=self.processes.get("dy_ptz5"),
            xs=0.5086,
            secondary_dataset="dy_ptz5_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("dy_ptz6",
            folder=p + "DYJetsToLL_LHEFilterPtZ-650ToInf-amcatnloFXFX",
            process=self.processes.get("dy_ptz6"),
            xs=0.040981055,
            secondary_dataset="dy_ptz6_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        Dataset("dy_0j",
            folder=p + "DYJetsToLL_0J-amcatnloFXFX",
            process=self.processes.get("dy_0j"),
            xs=5090.0,
            secondary_dataset="dy_0j_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("dy_1j",
            folder=p + "DYJetsToLL_1J-amcatnloFXFX",
            process=self.processes.get("dy_1j"),
            xs=983.5,
            secondary_dataset="dy_1j_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("dy_2j",
            folder=p + "DYJetsToLL_2J-amcatnloFXFX",
            process=self.processes.get("dy_2j"),
            xs=353.6,
            secondary_dataset="dy_2j_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        # EWK
        Dataset("ewk_z",
            folder=p + "EWK_ZTo2L",
            process=self.processes.get("ewk_z"),
            xs=6.215,
            splitting=200000,
            secondary_dataset="ewk_z_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ewk_wplus",
            folder=p + "EWK_WplusToLNu",
            process=self.processes.get("ewk_wplus"),
            xs=39.05,
            secondary_dataset="ewk_wplus_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ewk_wminus",
            folder=p + "EWK_WminusToLNu",
            process=self.processes.get("ewk_wminus"),
            xs=32.05,
            secondary_dataset="ewk_wminus_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        ######################################## Top ##################################################
        ###############################################################################################

        # TT
        Dataset("tt_dl",
            folder=p + "TTTo2L2Nu",
            process=self.processes.get("tt_dl"),
            xs=88.29,
            merging={
                "tautau": 20,
                "mutau": 20,
                "etau": 40,
            },
            scaling=(0.908, 0.006),
            secondary_dataset="tt_dl_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("tt_sl",
            folder=p + "TTToSemiLeptonic",
            process=self.processes.get("tt_sl"),
            xs=365.34,
            merging={
                "tautau": 20,
                "mutau": 60,
                "etau": 40,
            },
            scaling=(0.908, 0.006),
            secondary_dataset="tt_sl_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("tt_fh",
            folder=p + "TTToHadronic",
            process=self.processes.get("tt_fh"),
            xs=377.96,
            scaling=(0.908, 0.006),
            secondary_dataset="tt_fh_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        # TW
        Dataset("st_tw_antitop",
            folder=p + "ST_tW_antitop_5f_InclusiveDecays",
            process=self.processes.get("tw"),
            xs=35.85,
            secondary_dataset="st_tw_antitop_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("st_tw_top",
            folder=p + "ST_tW_top_5f_InclusiveDecays",
            process=self.processes.get("tw"),
            xs=35.85,
            secondary_dataset="st_tw_top_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        # singleT
        Dataset("st_antitop",
            folder=p + "ST_t-channel_antitop_4f_InclusiveDecays",
            process=self.processes.get("singlet"),
            xs=80.95,
            secondary_dataset="st_antitop_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("st_top",
            folder=p + "ST_t-channel_top_4f_InclusiveDecays",
            process=self.processes.get("singlet"),
            xs=136.02,
            secondary_dataset="st_top_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        ######################################## Di- and Tri-boson ####################################
        ###############################################################################################

        # VV
        Dataset("zz_dl",
            folder=p + "ZZTo4L",
            process=self.processes.get("zz"),
            xs=1.26,
            secondary_dataset="zz_dl_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("zz_fh",
            folder=p + "ZZTo4Q",
            process=self.processes.get("zz"),
            xs=3.262,
            secondary_dataset="zz_fh_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("zz_lnu",
            folder=p + "ZZTo2L2Nu",
            process=self.processes.get("zz"),
            xs=0.564,
            secondary_dataset="zz_lnu_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("zz_qnu",
            folder=p + "ZZTo2Q2Nu",
            process=self.processes.get("zz"),
            xs=4.07,
            secondary_dataset="zz_qnu_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wz_lllnu",
            folder=p + "WZTo3LNu",
            process=self.processes.get("wz"),
            xs=4.43,
            secondary_dataset="wz_lllnu_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wz_lnuqq",
            folder=p + "WZTo1L1Nu2Q",
            process=self.processes.get("wz"),
            xs=10.71,
            secondary_dataset="wz_lnuqq_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wz_lnununu",
            folder=p + "WZTo1L3Nu",
            process=self.processes.get("wz"),
            xs=3.414,
            secondary_dataset="wz_lnununu_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wz_llqq",
            folder=p + "WZTo2Q2L",
            process=self.processes.get("wz"),
            xs=5.595,
            secondary_dataset="wz_llqq_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ww_llnunu",
            folder=p + "WWTo2L2Nu",
            process=self.processes.get("ww"),
            xs=12.178,
            secondary_dataset="ww_llnunu_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ww_lnuqq",
            folder=p + "WWTo1L1Nu2Q",
            process=self.processes.get("ww"),
            xs=49.997,
            secondary_dataset="ww_lnuqq_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ww_qqqq",
            folder=p + "WWTo4Q",
            process=self.processes.get("ww"),
            xs=51.723,
            secondary_dataset="ww_qqqq_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        # VVV
        Dataset("zzz",
            folder=p + "ZZZ",
            process=self.processes.get("zzz"),
            xs=0.0147,
            secondary_dataset="zzz_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wzz",
            folder=p + "WZZ",
            process=self.processes.get("wzz"),
            xs=0.057,
            secondary_dataset="wzz_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("www",
            folder=p + "WWW_4F",
            process=self.processes.get("www"),
            xs=0.209,
            secondary_dataset="www_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wwz",
            folder=p + "WWZ_4F",
            process=self.processes.get("wwz"),
            xs=0.168,
            secondary_dataset="wwz_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        ######################################## Others ###############################################
        ###############################################################################################

        # TTX
        Dataset("ttw_lnu",
            folder=p + "TTWJetsToLNu",
            process=self.processes.get("ttw"),
            xs=0.2043,
            secondary_dataset="ttw_lnu_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ttw_qq",
            folder=p + "TTWJetsToQQ",
            process=self.processes.get("ttw"),
            xs=0.4062,
            secondary_dataset="ttw_qq_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ttww",
            folder=p + "TTWW",
            process=self.processes.get("ttww"),
            xs=0.00698,
            secondary_dataset="ttww_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ttwz",
            folder=p + "TTWZ",
            process=self.processes.get("ttwz"),
            xs=0.002441,
            secondary_dataset="ttwz_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ttwh",
            folder=p + "TTWH",
            process=self.processes.get("ttwh"),
            xs=0.00158,
            secondary_dataset="ttwh_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ttzh",
            folder=p + "TTZH",
            process=self.processes.get("ttzh"),
            xs=0.00154,
            secondary_dataset="ttzh_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ttz_llnunu",
            folder=p + "TTZToLLNuNu_M-10",
            process=self.processes.get("ttz"),
            xs=0.2529,
            secondary_dataset="ttz_llnunu_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ttz_qq",
            folder=p + "TTZToQQ",
            process=self.processes.get("ttz"),
            xs=0.5297,
            secondary_dataset="ttz_qq_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("ttzz",
            folder=p + "TTZZ",
            process=self.processes.get("ttzz"),
            xs=0.001386,
            secondary_dataset="ttzz_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        ######################################## Higgs ###############################################
        ###############################################################################################

        ## ZH_HToBB_ZToLL and ZHToTauTau are in ZZ and ZH specific configurations 
        
        # ZH_hbb       # removed since the dataset is not available TODO FIXME
        # Dataset("zh_hbb_zqq",
        #     folder=p + "ZH_Hbb_Zqq",
        #     process=self.processes.get("zh_hbb"),# the associated process is defined separately in ZZ and ZH configs since the parent process is different in each case
        #     xs=0.36,
        #     secondary_dataset="zh_hbb_zqq_aux",
        #     # categorization_max_events=10000,
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),
            
        # WH_htt
        Dataset("wminush_htt",
            folder=p + "WminusHToTauTau_M125",
            process=self.processes.get("wh_htt"),
            # prefix="xrootd-cms.infn.it//",
            xs=0.0334,
            secondary_dataset="wminush_htt_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("wplush_htt",
            folder=p + "WplusHToTauTau_M125",
            process=self.processes.get("wh_htt"),
            # prefix="xrootd-cms.infn.it//",
            xs=0.05268,
            secondary_dataset="wminush_htt_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),    

        # vbf_htt (removed cause it takes very long and it's not in the datacard for HHbbtt) 
        # Dataset("vbf_htt",
        #     folder=p + "VBFHToTauTau_M125",
        #     process=self.processes.get("vbf_htt"),
        #     # prefix="xrootd-cms.infn.it//",
        #     xs=0.237,
        #     secondary_dataset="vbf_htt_aux",
        #     # categorization_max_events=10000,
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),

        # # ttH_hbb # [FIXME] Not available
        # Dataset("tth_bb",
        #     folder=p + "ttHTobb_M125",
        #     process=self.processes.get("tth_bb"),
        #     # prefix="xrootd-cms.infn.it//",
        #     xs=0.2953,
        #     secondary_dataset="tth_bb_aux",
        #     # categorization_max_events=10000,
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),
        # ttH_htt (not in the datacard)
        Dataset("tth_tautau",
            folder=p + "ttHToTauTau_M125",
            process=self.processes.get("tth_tautau"),
            # prefix="xrootd-cms.infn.it//",
            xs=0.031805,
            secondary_dataset="tth_tautau_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        # ttH_hnonbb (removed cause it takes very long and it's not in the datacard for HHbbtt) 
        # Dataset("tth_nonbb",
        #     folder=p + "ttHToNonbb_M125",
        #     process=self.processes.get("tth_nonbb"),
        #     # prefix="xrootd-cms.infn.it//",
        #     xs=0.17996,
        #     secondary_dataset="tth_nonbb_aux",
        #     # categorization_max_events=10000,
        #     prefix="eoscms.cern.ch//",
        #     tags=["ul", "nanoV10"]),

        # ggH_ZZ
        Dataset("ggH_ZZ",
            folder=p + "ggHToZZTo2L2Q",
            process=self.processes.get("ggH_ZZ"),
            # prefix="xrootd-cms.infn.it//",
            xs=28.87, # XSDB NLO
            secondary_dataset="ggH_ZZ_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        ######################################## HH bbtautau ##########################################
        ###############################################################################################

        # ggf
        Dataset("ggf_sm",
            folder=p + "GluGluToHHTo2B2Tau_node_SM",
            process=self.processes.get("ggf_sm"),
            xs=0.002268,
            secondary_dataset="ggf_sm_aux",
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        ######################################## Data #################################################
        ###############################################################################################

        # Tau 2016 HIPM
        Dataset("data_tau_a",
            folder=p + "Tau_Run2016B",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="B",
            splitting=-1,
            merging={
                "tautau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_tau_b",
            folder=p + "Tau_Run2016C",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="C",
            splitting=-1,
            merging={
                "tautau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_tau_c",
            folder=p + "Tau_Run2016D",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="D",
            splitting=-1,
            merging={
                "tautau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_tau_d",
            folder=p + "Tau_Run2016E",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="E",
            splitting=-1,
            merging={
                "tautau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_tau_e",
            folder=p + "Tau_Run2016F",
            selection="pairType == 2",
            process=self.processes.get("data_tau"),
            runEra="F",
            splitting=-1,
            merging={
                "tautau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        # SingleElectron 2016 HIPM
        Dataset("data_etau_a",
            folder=p + "SingleElectron_Run2016B",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="B",
            splitting=-1,
            merging={
                "etau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_etau_b",
            folder=p + "SingleElectron_Run2016C",
            process=self.processes.get("data_etau"),
            runEra="C",
            splitting=-1,
            merging={
                "etau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_etau_c",
            folder=p + "SingleElectron_Run2016D",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="D",
            splitting=-1,
            merging={
                "etau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_etau_d",
            folder=p + "SingleElectron_Run2016E",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="E",
            splitting=-1,
            merging={
                "etau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_etau_e",
            folder=p + "SingleElectron_Run2016F",
            selection="pairType == 1",
            process=self.processes.get("data_etau"),
            runEra="F",
            splitting=-1,
            merging={
                "etau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

        # SingleMuon 2016 HIPM
        Dataset("data_mutau_a",
            folder=p + "SingleMuon_Run2016B",
            selection="pairType == 0",
            process=self.processes.get("data_mutau"),
            runEra="B",
            splitting=-1,
            merging={
                "mutau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_mutau_b",
            folder=p + "SingleMuon_Run2016C",
            process=self.processes.get("data_mutau"),
            selection="pairType == 0",
            runEra="C",
            splitting=-1,
            merging={
                "mutau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_mutau_c",
            folder=p + "SingleMuon_Run2016D",
            process=self.processes.get("data_mutau"),
            selection="pairType == 0",
            runEra="D",
            splitting=-1,
            merging={
                "mutau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_mutau_d",
            folder=p + "SingleMuon_Run2016E",
            process=self.processes.get("data_mutau"),
            selection="pairType == 0",
            runEra="E",
            splitting=-1,
            merging={
                "mutau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),
        Dataset("data_mutau_e",
            folder=p + "SingleMuon_Run2016F",
            process=self.processes.get("data_mutau"),
            selection="pairType == 0",
            runEra="F",
            splitting=-1,
            merging={
                "mutau": 2,
            },
            # categorization_max_events=10000,
            prefix="eoscms.cern.ch//",
            tags=["ul", "nanoV10"]),

    ]
    datasets = ObjectCollection(datasets)

    return datasets